version: "3"

services:
  postgres:
    image: "postgres:9.6-alpine"
    volumes:
      - .postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=todoapp
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  todoapp:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/todoapp
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
